name: Docker CI/CD Pipeline

on:
push:
branches:
- main

jobs:
build:
runs-on: ubuntu-latest

steps:
  - name: Checkout Source Code
    uses: actions/checkout@v4

  - name: Build Docker Image
    run: docker build -t docker-app ./docker-app

deploy:
needs: build
runs-on: ubuntu-latest

steps:
  - name: Deployment Message
    run: echo "Deployment Stage Completed"
